### ISSUE TITLE
`list_objects_v2` not supported

### ISSUE THREAD

**Issue by pmarko1711** [aws/boto3-s3-access-grants-plugin#15]
I noticed that when I use [`list_objects_v2()`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/list_objects_v2.html) for a given bucket & prefix, the plugin issues a get-data-access API call for the whole bucket.

I think this is due to the [current way of constructing `s3_prefix` within `__get_s3_prefix()`](https://github.com/aws/boto3-s3-access-grants-plugin/blob/7ed0f6609a9daab3d33242283d27c9e904232b66/aws_s3_access_grants_boto3_plugin/s3_access_grants_plugin.py#L60). It will built s3 prefix only if there is a parameter `Key`. [`list_objects_v2()`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/list_objects_v2.html) however works with a parameter `Prefix`.

**Comment by nikitamsawant** [comment]
Hi pmarko1711,
Thank you for bringing this to our attention. We were able to reproduce the issue, and it was a bug. This should be patched as of release 1.1.0. Can you please upgrade and confirm your problem is resolved?
