### ISSUE TITLE
Not able to use the plugin to get objects from cross account s3 access grant - getting GetObject access denied

### ISSUE THREAD

**Issue by aswin2025** [aws/boto3-s3-access-grants-plugin#17]
Steps Taken:

**Cross-Account S3 Access Grant Setup**:
I used the s3 controltower get_access_data API to verify the cross-account setup, and it confirmed that the access grant is functioning correctly. Below is the code I used:
`response = client.get_data_access(
    AccountId='xxx',
    Target='s3:xx',
    Permission='READ'
)
`

**Attempt to Access S3 Objects via Studio Notebooks**:
From the cross account, I installed and registered the required plugin, then attempted to retrieve objects from S3 (s3 grant from account A) using the get_object API. Here’s the code I executed:

`import botocore.session
from aws_s3_access_grants_boto3_plugin.s3_access_grants_plugin import S3AccessGrantsPlugin

import boto3
import logging
session = boto3.Session()
s3_client = session.client('s3', region_name='eu-west-1')
plugin = S3AccessGrantsPlugin(s3_client, fallback_enabled=False)
plugin.register()

s3_client.get_object(Bucket='s3-xxx', Key='data/xx')
`

However, I encountered the following error: ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied.

**Comment by nikitamsawant** [comment]
Hi aswin2025,
Thank you for bringing this to our attention. We were able to reproduce the issue, and it was a bug. This should be patched as of release 1.1.0. Can you please upgrade and confirm your problem is resolved?
